spring:
  application:
    name: active-life-canada
  redis:
    host: localhost
    port: 6379
    session:
      store-type: redis
    password:
  artemis:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  datasource:
    url: jdbc:postgresql://localhost:5432/active_life_db
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
queue:
  name: active-life-queue
logging:
  level:
    root: error
    org.springframework: info
    org.springframework.security: trace

management:
  endpoint:
    health:
      show-details: always
      show-components: always

springdoc:
  show-actuator: true

server:
  port: 8080
  ssl:
    key-store: classpath:active-life-canada-keystore.jks
    key-store-password: changeit
    key-store-type: JKS
    trust-store: classpath:active-life-canada-truststore.jks
    trust-store-password: changeit
    trust-store-type: JKS
    client-auth: NEED  # Enforce two-way SSL



#stripe:
#  secretKey: sk_test_51QpaHIGxFYAFJSJhwbFX5vEuzeyHJWAOdh2aELdI1sFknAewV9brvKNUBDszgDLlvRmKzUr50XK5a2HOjThPWTTp00IZnYgcQE
#server:
#  port: 30002
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: java17
#    key-password: java17